### ISSUE TITLE
JSON Parsing bug when array object's last property is another array.

### ISSUE THREAD

**Issue by ESLKem** [PRGfx/mQscripts#3]
A bit of an array-ception, but I'll try my best to explain ^^

Consider you have an array of two objects. If the first object ends with a key:array property, the next object fails to be parsed.

JSON samples to illustrate:

- This bugs out (only the first object is parsed from the array): `[{"key1a":"value1a","array1a":[{"key2a":"value2a", "key3a":"value3a"}]},{"key1b":"value1b","array1b":[{"key2b":"value2b", "key3b":"value3b"}]}]`

- This works as intended: `[{"key1a":"value1a","array1a":[{"key2a":"value2a", "key3a":"value3a"}],"key4a": "value4a"},{"key1b":"value1b","array1b":[{"key2b":"value2b", "key3b":"value3b"}]}]`

**Comment by PRGfx** [comment]
I might look into that within the next days.
When I first encountered this behaviour, I hotfixed it with `FixedData=TextLib::Replace(_Data,"]}","] }");` in the library usage.

My theory is that the length of the parsed object is slightly off (compare 25f8286e23b4e9235086e4b7becf6a6a655e6fbf)
